# Generated by meteor-tupperware quickstart script 0.1.1
# https://github.com/chriswessels/meteor-tupperware

# Inherit from chriswessels/meteor-tupperware image
FROM quay.io/chriswessels/meteor-tupperware

# The maintainer of your app image
MAINTAINER Harrison Miller <harrison.miller@yale.edu>

# (optional) Bake runtime options into your image
# ENV MONGO_URL="mongodb://url" MONGO_OPLOG_URL="mongodb://oplog_url" ROOT_URL="http://yourapp.com"
